on: [push]
jobs:
  test:
    runs-on: codeberg-small
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/terraform-linters/setup-tflint@v6
        name: Setup TFLint
        with:
          tflint_version: v0.59.1
          cache: true
      - run: tflint --format=compact --chdir=terraform/
