on: [push]
jobs:
  test:
    runs-on: codeberg-small
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: https://github.com/terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.59.1
          cache: true
      - name: Lint Terraform files
        run: tflint --format=compact --chdir=terraform/

      - name: Lint Ansible files
        uses: https://github.com/ansible/ansible-lint@v25
        with:
          working_directory: ansible/
