# Our custom values for pg_createcluster(8)
# Occurrences of '%v' are replaced by the major version number,
# and '%c' by the cluster name. Use '%%' for a literal '%'.

data_directory = '/data/postgresql/%v/%c'
