---
- name: Configure system
  hosts: singleton
  gather_facts: true

  tasks:
    - name: Upgrade existing packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: safe

    - name: Install common packages
      ansible.builtin.apt:
        pkg:
          # Required for third-party apt repositories
          - ca-certificates
          - git

    - name: Reboot
      ansible.builtin.reboot: {}
