---
- name: Configure system
  hosts: singularity
  gather_facts: true

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 43200  # 12 hours

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - docker.io

    - name: Create a network
      community.docker.docker_network:
        name: service-bridge

    - name: Copy the config
      ansible.builtin.copy:
        src: ./assets/daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Reload docker.service
      ansible.builtin.systemd_service:
        name: docker.service
        state: restarted
