---
- name: Install Caddy
  hosts: singleton
  gather_facts: true

  tasks:
    - name: Create directory `/root/volume/caddy-config`
      ansible.builtin.file:
        path: /root/volume/caddy/etc/caddy
        state: directory
        mode: '0755'

    - name: Copy the Caddyfile
      ansible.builtin.copy:
        src: ./assets/Caddyfile
        dest: /root/volume/caddy/etc/caddy/Caddyfile
        owner: root
        group: root
        mode: u=rw,g=r,o=r

    - name: Start Caddy container
      community.docker.docker_container:
        name: caddy
        image: docker.io/caddy:2.10
        pull: always
        recreate: true
        networks:
          - name: service-bridge
        volumes:
          - /root/volume/caddy/config:/config
          - /root/volume/caddy/data:/data
          - /root/volume/caddy/etc/caddy:/etc/caddy
        restart_policy: unless-stopped
        ports:
          - 0.0.0.0:80:80/tcp
          - 0.0.0.0:443:443/tcp
          - 0.0.0.0:443:443/udp
