---
- name: Install PostgreSQL
  hosts: singularity
  gather_facts: true

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 43200  # 12 hours

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl

    - name: Create a `/usr/share/postgresql-common/pgdg` directory
      ansible.builtin.file:
        path: /usr/share/postgresql-common/pgdg
        state: directory
        mode: u=rwx,g=rx,o=rx

    - name: Add PostgreSQL's apt repository
      block:
        - name: Get the signing key
          ansible.builtin.get_url:
            url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
            dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
            mode: u=rw,g=r,o=r
        - name: Add apt repository
          ansible.builtin.apt_repository:
            repo: deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt noble-pgdg main

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install PostgreSQL 18
      ansible.builtin.apt:
        pkg:
          - postgresql-18
          - postgresql-18-postgis-3
          - postgresql-client-18

    # TODO: this is insecure; fix it.
    - name: Modify `pg_hba.conf` to trust all logins at localhost
      ansible.builtin.lineinfile:
        path: /etc/postgresql/18/main/pg_hba.conf
        regexp: 'host\s+all\s+all\s+127.0.0.1/32\s+scram-sha-256'
        line: 'host    all             all             127.0.0.1/32            trust'

    - name: Modify `pg_hba.conf` to trust all logins at the UNIX socket
      ansible.builtin.lineinfile:
        path: /etc/postgresql/18/main/pg_hba.conf
        regexp: 'local\s+all\s+all\s+peer'
        line: 'local   all             all                                     trust'

    - name: Restart postgresql.service
      ansible.builtin.systemd_service:
        name: postgresql.service
        state: restarted
