---
- name: Initialise PostgreSQL Database
  hosts: singularity
  gather_facts: true

  tasks:
    - name: Clone the repo
      ansible.builtin.git:
        repo: 'https://codeberg.org/socialmaps/api.git'
        dest: /root/socialmaps/api
        version: main
        single_branch: true
        update: true

    - name: Run scripts/init-db.sh
      ansible.builtin.command:
        chdir: /root/socialmaps/api
        cmd: ./scripts/init-db.sh
      register: init_db_out
      changed_when: init_db_out.rc == 0
