when:
  branch: main
  event: [push, pull_request, manual]

steps:
  - name: lint-ci
    image: docker.io/woodpeckerci/woodpecker-cli:v3.13.0-alpine
    commands:
      - woodpecker-cli lint --strict

  - name: tflint
    image: ghcr.io/terraform-linters/tflint
    commands:
      - ./scripts/tflint.sh

  - name: ansible-lint
    image: docker.io/python:3.14.3-trixie
    commands:
      - pip3 install ansible ansible-dev-tools
      - ./scripts/ansible-lint.sh
